name: Build/Release

# Set triggers
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 14.16.1
    - name: see directory
      run: ls
      
  build_on_win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master
      with:
        ref: master        
    - uses: actions/setup-node@master
      with:
        node-version: 14.16.1
    - name: see directory
      run: ls
