name: Build/Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 14.16.1
    - name: Install dependencies
      run: yarn install
    - name: Build on MacOS
      run: yarn dist:mac
    - name: See directory
      run: ls dist
      
  build_win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 14.16.1
    - name: Install dependencies
      run: yarn install
    - name: Build on Windows
      run: yarn dist:win
    - name: See directory
      run: ls dist
