name: release

on:
  push:
    tags:
      - '*'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_release_windows:
    name: build_release
    runs-on: windows-2016
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: actions/setup-node@master
        with:
          node-version: 14.16.1
      - name: Install dependencies
        run: yarn install
      - name: Build on Windows
        run: yarn dist:win
      - name: version
        run: echo "::set-output name=version::$(./bin/instasplit --version)"
        id: version
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./dist/Instasplit Setup 0.1.0.exe"
          asset_name: "Instasplit Setup 0.1.0.exe"
          asset_content_type: application/gzip
